### ISSUE TITLE
Icons reset

### ISSUE THREAD

**Issue by Lost0032** [eggonthebeat/IconHack#1]
Every time i exit and then play GD again all my hacked icons change to default. What do i do? Its kinda annoying to change my icons over and over again.

**Comment by eggonthebeat** [comment]
Do you have other mods/mod menus which includes icon unlock?

**Comment by Lost0032** [comment]
Nope. Only this icon hack.

**Comment by eggonthebeat** [comment]
Saving locked icons works fine for me... are you on a private server?

**Comment by Lost0032** [comment]
Also no. Im not using any mods or something like that (exept geode)

**Comment by Lost0032** [comment]
And btw, after using this icon hack i got a swing that i didnt even use and it is only unlockable in 2.21. i still dont have icon hack on, and the swing isnt dissapearing after rejoining.

**Comment by Strookyy** [comment]
Same here, icons reset. Not sure if this is because of GD update or possible a change to Gd's servers to validate icons?
