### ISSUE TITLE
Icons don't save on exit

### ISSUE THREAD

**Issue by JoJo7447** [eggonthebeat/IconHack#5]
When I leave the game, all my icons get set to the default ones and I have to choose all my hacked icons again. It's pretty annoying to have to set them all again each time I launch the game so if you can't make an automatic save of hacked icons, please consider at least making some kind of "save file" thing where you could just save a set of icons and load it anytime.

PS: While writing that, I just thought that this could be a non-hacked mod as well, it would be pretty useful for people that change their icons often.

**Comment by eggonthebeat** [comment]
Will fix in the new next update. Should be approved tomorrow hopefully.
